require("pythonhubdev.core")
require("pythonhubdev.lazy")

vim.lsp.enable("basedpyright")
vim.lsp.enable("biome")
vim.lsp.enable("clangd")
vim.lsp.enable("cssls")
vim.lsp.enable("dockerls")
vim.lsp.enable("docker_compose_language_service")
vim.lsp.enable("docker_language_server")
vim.lsp.enable("gopls")
vim.lsp.enable("golangci_lint_ls")
vim.lsp.enable("harper_ls")
vim.lsp.enable("jinja_lsp")
vim.lsp.enable("jsonls")
vim.lsp.enable("lua_ls")
vim.lsp.enable("markdown_oxide")
vim.lsp.enable("ruff")
vim.lsp.enable("rust_analyzer")
vim.lsp.enable("sqls")
vim.lsp.enable("sqruff")
vim.lsp.enable("superhtml")
vim.lsp.enable("svelte")
vim.lsp.enable("tailwindcss")
vim.lsp.enable("taplo")
vim.lsp.enable("ts_ls")
vim.lsp.enable("yamlls")
vim.lsp.enable("zuban")

vim.g.neovide_opacity = 0.8
vim.g.neovide_normal_opacity = 1.0
